* Fix a bug in Authors extension ($ missing) * Comment out Authors extension. Method creditlink() appears to be missing.
Fatal error: Call to undefined function creditlink() in D:\mediawiki\phase3\extensions\uniwiki\Authors\Authors.php on line 83

git-svn-id: http://svn.wikimedia.org/svnroot/mediawiki/trunk@43031 dd0e9695-b195-4be7-bd10-2dea1a65a6b6